- name: Delete VM
  hosts: "{{  w_host | default('test') }}"
  vars:
  - pve-vars/pve.yml
  tasks:
    - name: Remove VM configuration
      community.general.proxmox_kvm:
        api_user: '{{ user }}'
        api_password: '{{ secret }}'
        api_host: '{{ hosts }}'
        name: '{{ vm_name }}'
        node: '{{ pvenode }}'
        state: absent
    